### ISSUE TITLE
descriptive User-Agent

### ISSUE THREAD

**Issue by jcarbaugh** [istrategylabs/imp-sentry#1]
https://github.com/istrategylabs/imp-sentry/blob/master/imp-sentry.nut#L16

It's generally good internet etiquette to use User-Agent as a way to report to the server who you are. Consider setting this to something like `imp-sentry/<version>` instead of `http-post/1.0`.

This might need to be the same as `sentry-client` in the XSentryAuth header.

**Comment by tguidon** [comment]
Gotcha, good point to learn. Updated and it works.
